channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=2.0.0
  - pandas
  - numba
  - pymzml
  - sortedcollections
  - pip:
    - xmltodict
    - requests
    - scipy
    - tqdm
    - pyteomics